config/routes.rb
Rails.application.routes.draw do
  put '/containers/:id/start', to: 'containers#start', as: 'start_container'
  put '/containers/:id/stop', to: 'containers#stop', as: 'stop_container'
  resources :containers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'containers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/container.rb
class Container < ApplicationRecord
  validates :name, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9_-]+\z/ }
  after_update { broadcast_update_to 'containers' }

  def docker_container
    Docker::Container.get(name)
  rescue Docker::Error::NotFoundError
    nil
  end

  def docker_status
    info = docker_container&.info
    info&.dig('State', 'Status')
  rescue Docker::Error::NotFoundError
    'missing'
  end

  def refresh_status
    update(status: docker_status)
  end

  def log_timestamp
    $redis.get("last_log_timestamp_#{id}").to_i
  end

  def set_log_timestamp
    $redis.set("last_log_timestamp_#{id}", Time.now.to_i)
  end

  def reset_log_timestamp
    $redis.del("last_log_timestamp_#{id}").to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: %i[show edit update destroy start stop]

  # GET /containers or /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1 or /containers/1.json
  def show
    @container.refresh_status
    @container.reset_log_timestamp
  end

  # GET /containers/new
  def new
    @container = Container.new
  end

  # GET /containers/1/edit
  def edit; end

  # POST /containers or /containers.json
  def create
    @container = Container.new(container_params)

    respond_to do |format|
      if @container.save
        format.html { redirect_to container_url(@container), notice: 'Container was successfully created.' }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1 or /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to container_url(@container), notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1 or /containers/1.json
  def destroy
    @container.destroy!

    respond_to do |format|
      format.html { redirect_to containers_url, notice: 'Container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start
    ContainerJob.perform_later(@container, :start)
    redirect_to container_url(@container), notice: 'Starting container...'
  end

  def stop
    ContainerJob.perform_later(@container, :stop)
    redirect_to container_url(@container), notice: 'Stopping container...'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_container
    @container = Container.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def container_params
    params.require(:container).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_container.html.erb
<div id="<%= dom_id container %>">
  <h2 class="text-2xl font-medium">
    <%= container.name %>
  </h2>
  <div class="my-5">
    <div class="flex items-center">
      <%= button_to "Start", start_container_path(container), method: :put, class: "rounded-md py-2 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      <%= button_to "Stop", stop_container_path(container), method: :put, class: "rounded-md py-2 px-5 bg-red-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  </div>
  <p class="my-5">
    <strong class="font-medium"> Status: </strong> <span class="<%= container.status == 'running'  ? 'text-green-500' : 'text-red-500' %>"> <%= container.status %> </span>
  </p>

</div>

app/views/containers/_form.html.erb
<%= form_with(model: container) do |form| %>
  <% if container.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
        <% container.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full' %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-old text-4xl">Editing container</h1>
  <%= render "form", container: @container %>

  <br>

  <div>
    <%= link_to "Show this container", @container, class: "ml-2 rounded-lg py-3 px-5 bg-gray-200" %> |
    <%= link_to "Back to containers", containers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-200" %>
  </div>
</div>

app/views/containers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
      <%= notice %>
    </p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Containers</h1>
    <%= link_to "New container", new_container_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="containers" class="min-w-full">
    <% @containers.each do |container| %>
      <%= render container %>
      <%= link_to "Show this container", container, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to "Edit this container", edit_container_path(container), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-5">
    <% end %>
  </div>
</div>

app/views/containers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Container</h1>
  <%= render "form", container: @container %>
  <%= link_to "Back to containers", containers_path, class: "ml-2 rounded-lg py-3 px-5" %>
</div>

app/views/containers/show.html.erb
<%= turbo_stream_from "containers" %>
<div class="w-full">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
        <%= notice %>
      </p>
    <% end %>
    <%= render @container %>
    <%= link_to "Edit this container", edit_container_path(@container), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this container", container_path(@container), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to containers", containers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

<div data-controller="console" data-console-id-value="<%= @container.id %>" id="terminal"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <main class="container mx-auto mt-25 px-5">
      <%= yield %>
    </main>
  </body>
</html>